### ISSUE TITLE
refactor: 대회페이지 수정사항 적용

### ISSUE THREAD

**Issue by JeonGAMJA** [OZ-Coding-School/oz_02_collabo-007#129]
### Issue

- Group: `FE`
- Type: `refactor`

### TO-DO

1. [ ] compCard 우상단 상세보기 코멘트
2. [x] 카드영역 대회버튼 영역 Link 나누기
3. [x] 대회버튼 종류에 따라 신청 or 현황으로 이동
4. [x] 대회 filter option에서 status 전체 삭제
5. [x] constants 분리
