### ISSUE TITLE
refactor: competition,compList 리팩토링

### ISSUE THREAD

**Issue by JeonGAMJA** [OZ-Coding-School/oz_02_collabo-007#137]
### Issue

- Group: `FE`
- Type: `refactor`

### TO-DO

1. [x] select 버그 수정
2. [x] 상수 null 부분 수정
3. [x] compListSection 하위 디렉토리 분리
