### ISSUE TITLE
refactor : 코드 리팩토링 , 미사용 상수 제거, 스켈레톤 작업

### ISSUE THREAD

**Issue by Hyunkyung1231** [OZ-Coding-School/oz_02_collabo-007#155]
### Issue

- Group: `FE`
- Type: `refactor`

### TO-DO

1. [x] 스켈레톤 추가
2. [x] 미사용 상수 제거
3. [x] 대회 조회 페이지 필터링 오류 fix
4. [x] 홈화면에서 대회조회 페이지 분기처리
5. [x] 내가 참가 신청한 대회 참가대기중, 미정 분기처리
