### ISSUE TITLE
Refactor: Input 공통 컴포넌트

### ISSUE THREAD

**Issue by JeonGAMJA** [OZ-Coding-School/oz_02_collabo-007#16]
### Issue
- Group: `FE`
- Type: `refactor`

### TO-DO
1. [x] Input쪽에 다이나믹 클래스 형태로 컬러 넣은 부분 수정
2. [x] label, helperText core로 분리 후 부착해서 module 생성
3. [x] label 데이터 안들어오면 생성되지 않게 변경
