### ISSUE TITLE
refactor: 내 전적 페이지 수정

### ISSUE THREAD

**Issue by JeonGAMJA** [OZ-Coding-School/oz_02_collabo-007#169]
### Issue

- Group: `FE`
- Type: `refactor`

### TO-DO

1. [x] 인풋 텍스트 사이즈 16px로 변경
2. [x] getMyRecord API 연동
3. [x] 내 전적 페이지 데이터에 맞춰서 컴포넌트 수정
