### ISSUE TITLE
refactor: 유저프로필카드 수정

### ISSUE THREAD

**Issue by JeonGAMJA** [OZ-Coding-School/oz_02_collabo-007#184]
### Issue

- Group: `FE`
- Type: `feature`, `bug`, `delete`

### TO-DO

1. [ ] 프로필 컴포넌트 수정
2. [x] ComCard 참가 대기중 => 입금 대기중으로 멘트 변경
3. [ ] 버그 찾는대로 수정
