### ISSUE TITLE
feat: 유저 프로필 랭킹 추가, competition 타입 리팩토링, 팀 랭킹 데이터 추가

### ISSUE THREAD

**Issue by JeonGAMJA** [OZ-Coding-School/oz_02_collabo-007#186]
### Issue

- Group: `FE`
- Type: `feature`

### TO-DO

1. [x] api 연동
2. [x] 레이아웃 구현
3. [x] competition 타입 리팩토링
4. [x] 팀 랭킹 데이터 추가
5. [x] 참가 대기중 => 입금 대기중으로 멘트 변경
