### ISSUE TITLE
feat: 대회 상세정보 페이지 마크업

### ISSUE THREAD

**Issue by HY2OK** [OZ-Coding-School/oz_02_collabo-007#28]
### Issue

- Group: `FE`
- Type: `feature`

### TO-DO

1. [x] 대회 상세 정보 페이지 마크업
2. [x] 대회 신청 페이지 마크업
3. [x] 파트너 검색 모달
4. [x] 대회 신청 완료 페이지 마크업
5. [x] 대회 현황 페이지 마크업
6. [x] 대회 결과 페이지 마크업
