### ISSUE TITLE
feat: 마이페이지 최근 참가 대회 마크업

### ISSUE THREAD

**Issue by JeonGAMJA** [OZ-Coding-School/oz_02_collabo-007#31]
### Issue

- Group: `FE`
- Type: `feature`

### TO-DO

1. [ ] 최근 참가 대회 마크업
2. [ ] 홈페이지 카드 width-screen 수정
3. [ ] 로그인페이지 백그라운드 scroll로 수정
