### ISSUE TITLE
refactor: 로그인 페이지

### ISSUE THREAD

**Issue by JeonGAMJA** [OZ-Coding-School/oz_02_collabo-007#49]
### Issue

- Group: `FE`
- Type: `feature`, `bug`, `delete`

### TO-DO

1. [x] 로그인 실패시 ui
2. [x] 창 진입시 id input 포커싱
3. [x] 에러메시지 위치 수정
