### ISSUE TITLE
refactor: 홈페이지,로그인,마이페이지 유저 프로필

### ISSUE THREAD

**Issue by JeonGAMJA** [OZ-Coding-School/oz_02_collabo-007#56]
### Issue

- Group: `FE`
- Type: `feature`

### TO-DO

1. [x] 로그인 포커스 버그 수정
2. [x] fetch caching
3. [x] fetch 수정
4. [x] Image 태그 size 기입
5. [x] user 조건처리 수정
6. [x] type 파일로 분리
7. [ ] any 부분 타입 지정 // competition api 형태 보고 수정해야 할듯
8. [x] CompList flexDirection tailwind merge로 수정
9. [x] home main CompList > map으로 수정
